apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
    env: prod
    kind: svc
  name: auth-svc
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: auth
    env: prod
    kind: pod
  type: ClusterIP
