apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
    env: prod
    type: loadbalancer
  name: frontend-svc
  namespace: default
spec:
  ports:
  - nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
    env: prod
    type: pod
  type: LoadBalancer
