apiVersion: v1
kind: Service
metadata:
  labels:
    app: task
    env: prod
    type: clusterip
  name: task-svc
  namespace: default
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: task
    env: prod
    type: pod
  type: ClusterIP
